export default [
    {
        _id: "123",
        topic: 'Web Development',
        userName: 'ReactJS',
        time: '2h',
        title: 'React.js is a component based front end library that makes it very easy to build Single Page Applications or SPAs',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png',
        tweets: '12k',
    },
    {
        _id: "234",
        topic: '',
        userName: 'JavaScript',
        time: '1 day',
        title: 'JavaScript is programming language that can run on browsers as well as desktops',
        image: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png',
        tweets: '123K',
    },
    {
        _id: "345",
        topic: 'Web Development',
        userName: '',
        title: 'jQuery',
        time: 'last week',
        image: 'https://cdn.iconscout.com/icon/free/png-512/jquery-10-1175155.png',
        tweets: '122K',
    },
    {
        _id: "456",
        topic: 'Web Development',
        userName: 'NodeJS',
        title: '',
        time: 'last month',
        image: 'https://cdn.iconscout.com/icon/free/png-512/node-js-1174925.png',
        tweets: '120K',
    },
];
